#!/usr/bin/env bash
set -euo pipefail

# Big-run launcher: 10k PPO updates on 8x8.
# Shape: horizon 32 × 256 agents × 10,000 updates = 81,920,000 impressions.
# This prioritizes optimizer-update count over a giant rollout batch.

CHAIN_REACTION_TOTAL_TIMESTEPS="${CHAIN_REACTION_TOTAL_TIMESTEPS:-81920000}" \
CHAIN_REACTION_BOARD_SIZE="${CHAIN_REACTION_BOARD_SIZE:-8}" \
CHAIN_REACTION_HORIZON="${CHAIN_REACTION_HORIZON:-32}" \
CHAIN_REACTION_TOTAL_AGENTS="${CHAIN_REACTION_TOTAL_AGENTS:-256}" \
CHAIN_REACTION_MINIBATCH_SIZE="${CHAIN_REACTION_MINIBATCH_SIZE:-8192}" \
CHAIN_REACTION_UPDATE_EPOCHS="${CHAIN_REACTION_UPDATE_EPOCHS:-1}" \
CHAIN_REACTION_MAX_TURNS="${CHAIN_REACTION_MAX_TURNS:-136}" \
CHAIN_REACTION_CHECKPOINT_INTERVAL="${CHAIN_REACTION_CHECKPOINT_INTERVAL:-500}" \
CHAIN_REACTION_LOG_INTERVAL="${CHAIN_REACTION_LOG_INTERVAL:-100}" \
CHAIN_REACTION_EVAL_INTERVAL="${CHAIN_REACTION_EVAL_INTERVAL:-500}" \
CHAIN_REACTION_EVAL_GAMES="${CHAIN_REACTION_EVAL_GAMES:-128}" \
CHAIN_REACTION_WANDB="${CHAIN_REACTION_WANDB:-1}" \
CHAIN_REACTION_WANDB_GROUP="${CHAIN_REACTION_WANDB_GROUP:-pygame-playable-8x8}" \
CHAIN_REACTION_WANDB_NAME="${CHAIN_REACTION_WANDB_NAME:-8x8-10k-updates}" \
CHAIN_REACTION_WANDB_TAGS="${CHAIN_REACTION_WANDB_TAGS:-8x8,torch-ppo,10k-updates,gradnorm}" \
bash "$(dirname "$0")/train.sh"
